extends: 
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
parserOptions:
  project: ./tsconfig.json
  sourceType: module
  ecmaVersion: 13
rules:
  brace-style: off
  "@typescript-eslint/brace-style": 
    - error
    - stroustrup
  react/react-in-jsx-scope:
    off
  no-unused-vars:
    off
  "@typescript-eslint/no-unused-vars":
    off